### PR TITLE
WIP: FEAT: add Service Bus plugin to enrich outgoing messages with correlation information

### PR DESCRIPTION
**Pull request by stijnmoreels**
Relates to #22

### CODE REVIEW

**Comment by stijnmoreels** [comment]
Just pushed this bc was not sure what it was again that we would need for this one.
I guess it's not entirely correct?

**Comment by tomkerkhove** [comment]
Approach is good, but we cannot inject the correlation info as it's scoped to a single message. Since the plugin is only registered once it should dynamically get the required correlation info on the fly

**Comment by tomkerkhove** [comment]
Or if we don't like that; we can provide an accessor that abstracts this for us but should be fetched every time.

**Comment by stijnmoreels** [comment]
> Approach is good, but we cannot inject the correlation info as it's scoped to a single message. Since the plugin is only registered once it should dynamically get the required correlation info on the fly

From where? The pump? Should we register the correlation in the services? But then what about parallel processing of messages...

**Comment by tomkerkhove** [comment]
We should fetch it from the DI container since we register it there but I might be mistaken with Web API.

Bottom line is, how it is now it will not pass the correct correlation info.

**Comment by stijnmoreels** [comment]
> We should fetch it from the DI container since we register it there but I might be mistaken with Web API.
> 
> Bottom line is, how it is now it will not pass the correct correlation info.

I think we better check this offline bc I'm not sure if I get it completly.

**Comment by tomkerkhove** [comment]
What I was referring to was a plugin that works similar to our recent enricher: https://github.com/arcus-azure/arcus.webapi/blob/fdabfcec041afafc8784d6abe9a2507c5e66c781/src/Arcus.WebApi.Telemetry.Serilog/Correlation/CorrelationInfoEnricher.cs

Services are passed, correlation is retrieved on a per-message basis and done. Unless we don't register correlation info in messaging yet of course.

**Pull request closed without merging**
