### PR TITLE
chore(move): message handling types to abstractions projects

### LINKED ISSUE #153: Move message handling types to abstractions projects
**Is your feature request related to a problem? Please describe.**
The Azure Service Bus message pump project contains several message handling abstractions that is now tightly-coupled to the message pump project. It would be good to extract these interfaces in a separate project.

**Describe the solution you'd like**
* Move the `MessageHandling` types from the `Arcus.Messaging.Pumps.Abstractions` to the `Arcus.Messaging.Abstractions` project/namespace
* Move the `MessageHandling` types from the `Arcus.Messaging.Pumps.ServiceBus` to the `Arcus.Messaging.ServiceBus.Abstractions` project/namespace.

### PR DESCRIPTION
**Pull request by stijnmoreels**
As we discovered while extracting the message routers, it would be better that we extracted the message handling first into abstractions projects.

- `Arcus.Messaging.Pumps.ServiceBus.MessageHandling` becomes `Arcus.Messaging.ServiceBus.Abstractions.MessageHandling`
- `Arcus.Messaging.Pumps.MessagingHandling` becomes `Arcus.Messaging.Abstractions.MessageHandling`

Closes #153

### CODE REVIEW

**Comment by tomkerkhove** [comment]
> As we discovered while extracting the message routers, it would be better that we extracted the message handling first into abstractions projects.
> 
> * `Arcus.Messaging.Pumps.ServiceBus.MessageHandling` becomes `Arcus.Messaging.ServiceBus.Abstractions.MessageHandling`
> * `Arcus.Messaging.Pumps.MessagingHandling` becomes `Arcus.Messaging.Abstractions.MessageHandling`
> 
> Closes #153

What if we use this? Doesn't it feel more natural?

- `Arcus.Messaging.Pumps.ServiceBus.MessageHandling` becomes `Arcus.Messaging.Abstractions.MessageHandling.ServiceBus` 
- `Arcus.Messaging.Pumps.MessagingHandling` becomes `Arcus.Messaging.Abstractions.MessageHandling`

**Comment by tomkerkhove** [comment]
This is a breaking change, are you planning on shipping 2.0?

**Comment by stijnmoreels** [comment]
> This is a breaking change, are you planning on shipping 2.0?

No, this is for v1.0, right?

**Comment by stijnmoreels** [comment]
> > As we discovered while extracting the message routers, it would be better that we extracted the message handling first into abstractions projects.
> > 
> > * `Arcus.Messaging.Pumps.ServiceBus.MessageHandling` becomes `Arcus.Messaging.ServiceBus.Abstractions.MessageHandling`
> > * `Arcus.Messaging.Pumps.MessagingHandling` becomes `Arcus.Messaging.Abstractions.MessageHandling`
> > 
> > Closes #153
> 
> What if we use this? Doesn't it feel more natural?
> 
> * `Arcus.Messaging.Pumps.ServiceBus.MessageHandling` becomes `Arcus.Messaging.Abstractions.MessageHandling.ServiceBus`
> * `Arcus.Messaging.Pumps.MessagingHandling` becomes `Arcus.Messaging.Abstractions.MessageHandling`

Ah, yes, sorry, that's indeed more natural. And when we introduce EventHub and it will need also some custom message handling, we can easily add it. I see your point, I'll change that.

**Comment by stijnmoreels** [comment]
Done moving to your suggestion!

**Review by tomkerkhove — APPROVED** [review]

**Pull request merged**
