### PR TITLE
Chore - update Messaging projects with netcore3.0 FrameworkReference

### PR DESCRIPTION
**Pull request by stijnmoreels**
Relates to https://github.com/arcus-azure/arcus/issues/50

### CODE REVIEW

**Comment by stijnmoreels** [comment]
Hmm, the `Arcus.Messaging.ServiceBus.Core` references a project that targets both netstandard and netcore. But the project itself only targets netstandard. Is that good?

**Comment by tomkerkhove** [comment]
Normally we should have enough with the netstandard reference, can you clean that up and see if everything still works please?

**Comment by stijnmoreels** [comment]
>> Hmm, the Arcus.Messaging.ServiceBus.Core references a project that targets both netstandard and netcore. But the project itself only targets netstandard. Is that good?
>
> Normally we should have enough with the netstandard reference, can you clean that up and see if everything still works please?

What do you mean with "clean up"? I didn't change the project target framework. So it's already just referencing netstandard.

**Comment by tomkerkhove** [comment]
Ah misread, then we are good to go.

**Pull request merged**
