### PR TITLE
feat: use message handler options to pass-in az servicebus receiver

### LINKED ISSUE #195: Move `ServiceBusReceiver` to options model for furture-proof message routing
**Is your feature request related to a problem? Please describe.**
Move our `ServiceBusReceiver` model from the router signature to an options model so that we are more safe in the future when we want to add stuff from the Azure Functions/message pump to the router.

**Describe alternatives you've considered**
Adding new stuff to the signature, but that requires breaking changes.

### PR DESCRIPTION
**Pull request by stijnmoreels**
Pass-in the `ServiceBusReceiver` via an options model, so can more easily change things later.

Closes #195

### CODE REVIEW

**Comment by stijnmoreels** [comment]
Let me know what you think of this solution. Consumers that uses our router outside the message pump, and uses specific Azure Service Bus operations (dead letter, complete, ...) will have to pass-in the `ServcieBusReceiver` via the options now.

**Comment by tomkerkhove** [comment]
As and end-user, I won't see this change - Right?

**Comment by stijnmoreels** [comment]
> As and end-user, I won't see this change - Right?

When using the message pump, yeah , no chance there. If we support Azure Functions in the future, they will have to pass it along via the options.

**Comment by tomkerkhove** [comment]
> When using the message pump, yeah , no chance there. If we support Azure Functions in the future, they will have to pass the receiver along via the options.
How is that? Wouldn't we create it for them? Because in a function there is no such thing as the client but rather done through the bindings, no?

**Comment by stijnmoreels** [comment]
> When using the message pump, yeah , no chance there. If we support Azure Functions in the future, they will have to pass the receiver along via the options.
> > How is that? Wouldn't we create it for them? Because in a function there is no such thing as the client but rather done through the bindings, no?

Right now, if we want to make use of our message handlers in an Azure Function, it would look like this:

```csharp
public class OrderFunction
{
    private readonly IAzureServiceBusMessageRouter _messageRouter;

    public OrderFunction(IAzureServiceBusMessageRouter messageRouter)
    {
        _messageRouter = messageRouter;
        JobId = Guid.NewGuid().ToString();
    }

    public string JobId { get; }

    [FunctionName("orders")]
    public async Task Run(
        [ServiceBusTrigger("queue-name", Connection = "ConnectionString")] ServiceBusReceivedMessage message,
        ServiceBusReceiver receiver,
        ILogger logger,
        CancellationToken cancellationToken)
    {
        var properties = AzureServiceBusSystemProperties.CreateFrom(message);
        var context = new AzureServiceBusMessageContext(message.MessageId, JobId, properties, message.ApplicationProperties); 
        MessageCorrelationInfo correlationInfo = message.GetCorrelationInfo();

        // 1. routing message without the possibility to call 'dead letter', 'complete' during the message handling.
        await _messageRouter.RouteMessageAsync(message, context, correlationInfo, cancellationToken);

        // 2. routing message with the possibilty to call 'dead letter', 'complete' during the message handling.
        await _messageRouter.RouteMessageAsync(message, context, correlationInfo, cancellationToken, options =>
        {
            options.ServiceBusReceiver = receiver;
        });
    }
}
````

**Comment by tomkerkhove** [comment]
I'd love to make 2 more user friendly though. Options is good for internal stuff but for this I'd rather have it as a parameter since it's "required".

**Comment by stijnmoreels** [comment]
> I'd love to make 2 more user friendly though. Options is good for internal stuff but for this I'd rather have it as a parameter since it's "required".

Ok, then we can actually abandon this PR, as that's how it now is.

**Pull request closed without merging**
